# CTB Global Configuration
# Version: 1.0.0
# Repository: client-subhive

meta:
  ctb_version: "1.0.0"
  repo_type: "parent"
  repo_name: "client-subhive"
  repo_slug: "djb258/client"
  created: "2025-10-23"
  last_sync: null

structure:
  ctb:
    sys:
      description: "System & Infrastructure"
      subdirs:
        - scripts
        - tools
        - factory
        - mechanic
        - mcp-servers
        - tests
        - global-factory
    ai:
      description: "AI & Agent Configurations"
      subdirs:
        - agents
        - modules
        - packages
    data:
      description: "Data & Database"
      subdirs:
        - db
        - firebase
    docs:
      description: "Documentation"
      subdirs: []
    ui:
      description: "User Interface"
      subdirs:
        - src
        - components
        - pages
        - apps
        - api
    meta:
      description: "Metadata & Configuration"
      subdirs:
        - workflows
        - doctrine
        - ops
        - config
        - templates
  logs:
    description: "Application Logs"
    subdirs:
      - compliance
      - sync
      - errors

doctrine_enforcement:
  enabled: true
  ctb_factory: "ctb/sys/global-factory/"
  auto_sync: true
  min_score: 70
  composio_scenario: "CTB_Compliance_Cycle"
  strict_mode: false
  auto_fix: true

compliance:
  checks:
    - name: "ctb_structure"
      description: "Verify CTB directory structure exists"
      severity: "critical"
      auto_fix: true
      weight: 40
    - name: "path_references"
      description: "Check all paths use CTB structure"
      severity: "high"
      auto_fix: false
      weight: 20
    - name: "documentation"
      description: "Ensure CTB_INDEX.md is up to date"
      severity: "medium"
      auto_fix: true
      weight: 15
    - name: "global_config"
      description: "Verify global-config.yaml exists and is valid"
      severity: "high"
      auto_fix: false
      weight: 15
    - name: "logs_directory"
      description: "Ensure logs directory exists with proper structure"
      severity: "low"
      auto_fix: true
      weight: 10

  enforcement_level: "warn"  # Options: strict, warn, disabled
  fail_on_violation: false
  block_commit_on_fail: false

  reports:
    directory: "logs/compliance"
    format: "json"
    retention_days: 90
    include_details: true

  scoring:
    perfect: 100
    passing: 90
    warning: 75
    failing: 0

sync:
  enabled: true
  schedule: "daily"  # Options: hourly, daily, weekly, manual
  auto_pull: true
  auto_push: false

  sources:
    - type: "github"
      repo: "djb258/client"
      branch: "main"
      path: "ctb/sys/global-factory"
      auth: "token"
    - type: "local"
      path: "ctb/sys/global-factory"

  targets:
    - destination: "ctb/sys/global-factory/"
      overwrite: false
      backup: true
    - destination: ".github/workflows/"
      overwrite: false
      backup: true

  filters:
    include:
      - "*.sh"
      - "*.py"
      - "*.yaml"
      - "*.yml"
      - "*.md"
    exclude:
      - "*.log"
      - "*.tmp"
      - "node_modules/**"

  notifications:
    on_sync: true
    on_failure: true
    on_changes: true
    channels:
      - type: "log"
        path: "logs/sync/sync.log"
      - type: "sidecar"
        endpoint: "${IMOCREATOR_SIDECAR_URL}/events"

integration:
  composio:
    enabled: true
    endpoint: "${COMPOSIO_API_URL}"
    token: "${COMPOSIO_API_KEY}"

    # Exposed Tasks for CTB Compliance Scripts
    tasks:
      - name: "ctb_tagger"
        description: "Inject CTB metadata blocks into files"
        script: "ctb/sys/global-factory/scripts/ctb_metadata_tagger.py"
        params:
          path: "ctb/"
          report: "CTB_TAGGING_REPORT.md"
        output:
          - "CTB_TAGGING_REPORT.md"
        schedule: "weekly"  # Can be: manual, daily, weekly, monthly

      - name: "ctb_auditor"
        description: "Generate CTB compliance audit reports"
        script: "ctb/sys/global-factory/scripts/ctb_audit_generator.py"
        params:
          path: "ctb/"
          report: "CTB_AUDIT_REPORT.md"
        output:
          - "CTB_AUDIT_REPORT.md"
          - "ctb/meta/ctb_registry.json"
        schedule: "weekly"
        min_score: 90

      - name: "ctb_remediator"
        description: "Automatically fix CTB compliance issues"
        script: "ctb/sys/global-factory/scripts/ctb_remediator.py"
        params:
          path: "ctb/"
          report: "CTB_REMEDIATION_SUMMARY.md"
        output:
          - "CTB_REMEDIATION_SUMMARY.md"
          - "ctb/meta/enforcement_rules.json"
        schedule: "weekly"
        auto_commit: true

    scenarios:
      - name: "CTB_Compliance_Cycle"
        description: "Complete CTB compliance workflow (weekly automated run)"
        trigger: "schedule"
        schedule: "0 2 * * 0"  # Every Sunday at 2 AM
        enabled: true
        actions:
          - action: "ctb_tagger"
            description: "Tag all untagged files with metadata"
            params:
              path: "ctb/"
              report: "CTB_TAGGING_REPORT.md"
            on_error: "continue"

          - action: "ctb_auditor"
            description: "Audit CTB structure for compliance"
            params:
              path: "ctb/"
              report: "CTB_AUDIT_REPORT.md"
            on_error: "fail"
            store_result: "audit_score"

          - action: "ctb_remediator"
            description: "Remediate compliance issues if score < 90"
            condition: "audit_score < 90"
            params:
              path: "ctb/"
              report: "CTB_REMEDIATION_SUMMARY.md"
            on_error: "continue"

          - action: "ctb_auditor"
            description: "Re-audit after remediation"
            condition: "audit_score < 90"
            params:
              path: "ctb/"
              report: "CTB_AUDIT_REPORT_POST_REMEDIATION.md"
            on_error: "continue"

          - action: "sync_global_scripts"
            description: "Sync global factory scripts"
            params:
              source: "ctb/sys/global-factory"
              dry_run: false
            on_error: "continue"

          - action: "generate_report"
            description: "Generate compliance summary"
            params:
              format: "json"
              notify: true
              store_in: "logs/compliance"
            on_error: "continue"

      - name: "CTB_Sync_Global"
        trigger: "schedule"
        schedule: "0 2 * * *"  # 2 AM daily (cron format)
        enabled: true
        actions:
          - action: "fetch_global_factory"
            params:
              source_repo: "djb258/client"
              source_path: "ctb/sys/global-factory"
          - action: "update_local_scripts"
            params:
              target: "ctb/sys/global-factory"
              backup: true
          - action: "notify_on_changes"
            params:
              channel: "log"

      - name: "CTB_Structure_Validation"
        trigger: "on_push"
        enabled: true
        actions:
          - action: "validate_structure"
            params:
              min_score: 90
          - action: "check_path_references"
            params:
              scan_extensions: [".js", ".ts", ".py", ".sh"]
          - action: "update_index"
            params:
              auto_generate: true

  heir:
    enabled: true
    schema_version: "HEIR/1.0"

    altitude_layers:
      - layer: 30
        description: "Strategic orchestration"
        compliance_role: "policy_enforcement"
        actions:
          - "define_compliance_policy"
          - "approve_global_changes"
          - "enforce_min_score"

      - layer: 20
        description: "Tactical processing"
        compliance_role: "sync_coordination"
        actions:
          - "coordinate_sync_operations"
          - "manage_conflicts"
          - "prioritize_checks"

      - layer: 10
        description: "Implementation"
        compliance_role: "file_operations"
        actions:
          - "copy_files"
          - "update_paths"
          - "create_structure"

      - layer: 5
        description: "Validation"
        compliance_role: "structure_verification"
        actions:
          - "verify_directories"
          - "check_file_existence"
          - "validate_yaml"

    error_handling:
      capture_all: true
      log_to_master: true
      retry_strategy: "exponential_backoff"
      max_retries: 3

  sidecar:
    enabled: true
    url: "${IMOCREATOR_SIDECAR_URL}"
    bearer_token: "${IMOCREATOR_BEARER_TOKEN}"

    events:
      - "ctb.structure.created"
      - "ctb.compliance.checked"
      - "ctb.compliance.passed"
      - "ctb.compliance.failed"
      - "ctb.sync.started"
      - "ctb.sync.completed"
      - "ctb.sync.failed"
      - "ctb.violation.detected"
      - "ctb.auto_fix.applied"

hooks:
  pre_commit:
    - name: "CTB Compliance Check"
      script: "ctb/sys/global-factory/compliance-check.sh"
      required: true
      blocking: false
      timeout: 30

  post_merge:
    - name: "CTB Sync Check"
      script: "ctb/sys/global-factory/sync-check.sh"
      required: false
      blocking: false
      timeout: 60

  pre_push:
    - name: "CTB Validation"
      script: "ctb/sys/global-factory/compliance-check.sh"
      required: true
      blocking: false
      timeout: 30

telemetry:
  enabled: true
  provider: "sidecar"
  endpoint: "${IMOCREATOR_SIDECAR_URL}/telemetry"

  events:
    - event: "ctb.structure.created"
      level: "info"
      include_metadata: true
    - event: "ctb.compliance.checked"
      level: "info"
      include_metadata: true
    - event: "ctb.compliance.passed"
      level: "info"
      include_metadata: true
    - event: "ctb.compliance.failed"
      level: "warning"
      include_metadata: true
    - event: "ctb.sync.completed"
      level: "info"
      include_metadata: false
    - event: "ctb.violation.detected"
      level: "error"
      include_metadata: true

  metadata:
    repo_name: true
    timestamp: true
    score: true
    user: false
    git_commit: true

paths:
  scripts: "ctb/sys/scripts"
  tools: "ctb/sys/tools"
  factory: "ctb/sys/factory"
  mechanic: "ctb/sys/mechanic"
  global_factory: "ctb/sys/global-factory"
  docs: "ctb/docs"
  logs: "logs"
  config: "ctb/meta/config"
  compliance_reports: "logs/compliance"
  sync_logs: "logs/sync"

maintenance:
  auto_cleanup: true
  archive_old_logs: true
  log_retention_days: 90
  temp_file_cleanup: true
  cleanup_schedule: "0 3 * * 0"  # 3 AM every Sunday

  cleanup_rules:
    - pattern: "logs/**/*.log"
      age_days: 90
      action: "archive"
    - pattern: "logs/compliance/*.json"
      age_days: 90
      action: "archive"
    - pattern: "*.tmp"
      age_days: 7
      action: "delete"

reference:
  global_factory:
    description: "Central repository for shared scripts and workflows"
    location: "ctb/sys/global-factory/"
    sync_source: "djb258/client:main:ctb/sys/global-factory"
    update_strategy: "pull_on_schedule"

  compliance_tools:
    - name: "compliance-check.sh"
      location: "ctb/sys/global-factory/compliance-check.sh"
      purpose: "Verify CTB structure compliance"
      usage: "./ctb/sys/global-factory/compliance-check.sh"

    - name: "sync-check.sh"
      location: "ctb/sys/global-factory/sync-check.sh"
      purpose: "Check for global factory updates"
      usage: "./ctb/sys/global-factory/sync-check.sh"

  documentation:
    - name: "CTB_INDEX.md"
      location: "CTB_INDEX.md"
      purpose: "Path mapping and structure documentation"
      update: "auto"

    - name: "global-config.yaml"
      location: "global-config.yaml"
      purpose: "Global CTB configuration"
      update: "manual"

environment:
  required_vars:
    - "IMOCREATOR_SIDECAR_URL"
    - "IMOCREATOR_BEARER_TOKEN"
  optional_vars:
    - "COMPOSIO_API_URL"
    - "COMPOSIO_API_KEY"
    - "GITHUB_TOKEN"

  defaults:
    IMOCREATOR_SIDECAR_URL: "http://localhost:8000"
    IMOCREATOR_BEARER_TOKEN: "local-dev-only"

version_control:
  track_changes: true
  changelog_path: "logs/ctb-changes.log"
  notify_on_update: true
  version_file: "ctb/.version"

# Custom rules specific to this repository
custom:
  imo_creator_integration: true
  garage_mcp_integration: true
  barton_doctrine_compliance: true

  special_directories:
    - path: "imo-creator/"
      type: "submodule"
      ctb_exempt: true
    - path: "garage-mcp/"
      type: "subsystem"
      ctb_exempt: true

  import_paths:
    preserve_relative: false
    enforce_ctb: true
    auto_update: false
