# ERD Metrics - Runtime Data Snapshot
# ===============================================================================
#
# PURPOSE: Current state of ERD tables for operational decision-making
# AUTHORITY: CC-04 (Process/Runtime)
# UPDATE FREQUENCY: Before any work session, minimum daily
#
# THIS FILE IS AUTO-UPDATED. Manual edits will be overwritten.
#
# ===============================================================================

# ─────────────────────────────────────────────────────────────────────────────────
# SYNC METADATA
# ─────────────────────────────────────────────────────────────────────────────────
sync:
  last_updated: '2026-02-11T00:00:00.000Z'
  updated_by: claude-code
  source: doppler://neon/client-subhive
  next_sync_due: '2026-02-12T00:00:00.000Z'
  frequency: daily
  stale_after_hours: 24
  auto_sync_on_session: true
  sync_frequency: on_demand
  notes: Run 'doppler run --project barton-outreach-core --config dev -- psql "$DATABASE_URL"' to query

# ─────────────────────────────────────────────────────────────────────────────────
# HUB IDENTITY
# ─────────────────────────────────────────────────────────────────────────────────
hub:
  hub_id: client-subhive
  hub_name: Client Intake & Vendor Export System
  sovereign_id: imo-creator
  erd_version: "2.3.0"
  schema: clnt
  database: Neon PostgreSQL
  adr: ADR-002-ctb-consolidated-backbone, ADR-004-renewal-downgraded-to-plan-support, ADR-005-client-projection-support

# ─────────────────────────────────────────────────────────────────────────────────
# TABLE METRICS (CTB Spoke Structure)
# ─────────────────────────────────────────────────────────────────────────────────
tables:
  s1_hub:
    - table_name: clnt.client_hub
      description: Root client identity (read-only after creation)
      spoke: S1
      leaf_type: FROZEN
      count: 0
      query: SELECT COUNT(*) FROM clnt.client_hub
    - table_name: clnt.client_master
      description: Client legal/business details
      spoke: S1
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.client_master
    - table_name: clnt.client_projection
      description: Per-client UI projection configuration (ADR-005)
      spoke: S1
      leaf_type: SUPPORT
      count: 0
      query: SELECT COUNT(*) FROM clnt.client_projection
  s2_plan:
    - table_name: clnt.plan
      description: Benefit plans with fixed cost tiers (canonical source of truth for active rates)
      spoke: S2
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.plan
    - table_name: clnt.plan_quote
      description: Received quotes. Multiple per benefit/year allowed. Promotion copies rates into plan.
      spoke: S2
      leaf_type: SUPPORT
      count: 0
      query: SELECT COUNT(*) FROM clnt.plan_quote
  s3_intake:
    - table_name: clnt.intake_batch
      description: Enrollment batch upload header
      spoke: S3
      leaf_type: STAGING
      count: 0
      query: SELECT COUNT(*) FROM clnt.intake_batch
    - table_name: clnt.intake_record
      description: Individual raw intake records
      spoke: S3
      leaf_type: STAGING
      count: 0
      query: SELECT COUNT(*) FROM clnt.intake_record
  s4_vault:
    - table_name: clnt.person
      description: Employee/dependent identity
      spoke: S4
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.person
    - table_name: clnt.election
      description: Benefit election bridge (person → plan)
      spoke: S4
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.election
  s5_vendor:
    - table_name: clnt.vendor
      description: Vendor identity per client
      spoke: S5
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.vendor
    - table_name: clnt.external_identity_map
      description: Internal-to-external ID translation
      spoke: S5
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.external_identity_map
  s6_service:
    - table_name: clnt.service_request
      description: Service ticket tracking
      spoke: S6
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.service_request
  s7_compliance:
    - table_name: clnt.compliance_flag
      description: Compliance flag tracking
      spoke: S7
      leaf_type: CANONICAL
      count: 0
      query: SELECT COUNT(*) FROM clnt.compliance_flag
  s8_audit:
    - table_name: clnt.audit_event
      description: Append-only system audit trail
      spoke: S8
      leaf_type: AUDIT
      count: 0
      query: SELECT COUNT(*) FROM clnt.audit_event

# ─────────────────────────────────────────────────────────────────────────────────
# VIEWS (Read-only, no table storage)
# ─────────────────────────────────────────────────────────────────────────────────
views:
  - view_name: clnt.v_client_dashboard
    description: Read-only dashboard surface for lovable.dev (ADR-005)
    spoke: S1
    source_tables: [client_hub, client_master, client_projection]

# ─────────────────────────────────────────────────────────────────────────────────
# AGGREGATE METRICS
# ─────────────────────────────────────────────────────────────────────────────────
aggregates:
  total_tables: 14
  total_views: 1
  total_records_all_tables: 0
  total_clients: 0
  total_persons: 0
  total_plans: 0
  total_plan_quotes: 0
  total_elections: 0
  total_vendors: 0
  total_audit_events: 0

# ─────────────────────────────────────────────────────────────────────────────────
# SYNC QUERIES (Reference)
# ─────────────────────────────────────────────────────────────────────────────────
queries:
  total_clients: |
    SELECT COUNT(*) FROM clnt.client_hub;
  total_persons: |
    SELECT COUNT(*) FROM clnt.person;
  total_plans: |
    SELECT COUNT(*) FROM clnt.plan;
  total_plan_quotes: |
    SELECT COUNT(*) FROM clnt.plan_quote;
  total_elections: |
    SELECT COUNT(*) FROM clnt.election;
  total_vendors: |
    SELECT COUNT(*) FROM clnt.vendor;
  total_audit_events: |
    SELECT COUNT(*) FROM clnt.audit_event;

# ─────────────────────────────────────────────────────────────────────────────────
# ALERTS / THRESHOLDS
# ─────────────────────────────────────────────────────────────────────────────────
thresholds:
  min_total_clients: 0
  max_null_rate: 5
  max_duplicate_rate: 2

alerts: []

# ===============================================================================
# DOCUMENT CONTROL
# ===============================================================================
document_control:
  template_version: "2.0.0"
  template_source: "imo-creator/templates/erd/ERD_METRICS.yaml.template"
  created: '2026-01-30'
  version: 2.3.0
  status: ACTIVE
  authority: CC-04
  change_protocol: "Auto-updated by sync process"
